# EDA: S&P 500 Earnings Transcripts

Goal:
- Load `kurry/sp500_earnings_transcripts` with `datasets`.
- Print basic dataset information for quick inspection.

In [1]:
!export HF_TOKEN="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"

'export' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

In [2]:
from datasets import load_dataset
import pandas as pd

DATASET_ID = "kurry/sp500_earnings_transcripts"

ds = None
try:
    ds = load_dataset(DATASET_ID)
    print(f"Loaded dataset: {DATASET_ID}")
except Exception as e:
    print("Failed to load dataset. If needed, run `huggingface-cli login` and check your network.")
    print(type(e).__name__, str(e))

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loaded dataset: kurry/sp500_earnings_transcripts

In [3]:
if ds is None:
    print("Dataset is not available yet. Re-run the previous cell after network/login is fixed.")
else:
    split_names = list(ds.keys())
    print("Dataset object:", ds)
    print("Splits:", split_names)
    print()

    for split in split_names:
        subset = ds[split]
        print(f"[{split}] rows={subset.num_rows}, columns={len(subset.column_names)}")
        print("Columns:", subset.column_names)
        print("Features:", subset.features)
        print("-" * 80)

Dataset object: DatasetDict({
    train: Dataset({
        features: ['symbol', 'quarter', 'year', 'date', 'content', 'structured_content', 'company_name', 'company_id'],
        num_rows: 33362
    })
})
Splits: ['train']

[train] rows=33362, columns=8
Columns: ['symbol', 'quarter', 'year', 'date', 'content', 'structured_content', 'company_name', 'company_id']
Features: {'symbol': Value('string'), 'quarter': Value('int64'), 'year': Value('int64'), 'date': Value('string'), 'content': Value('string'), 'structured_content': List({'speaker': Value('string'), 'text': Value('string')}), 'company_name': Value('string'), 'company_id': Value('float64')}
--------------------------------------------------------------------------------

In [4]:
if ds is None:
    print("Dataset is not available yet.")
else:
    primary_split = list(ds.keys())[0]
    subset = ds[primary_split]
    sample_size = min(5, subset.num_rows)
    sample_df = subset.select(range(sample_size)).to_pandas()

    print(f"Preview from split: {primary_split} (first {sample_size} rows)")
    display(sample_df)

Preview from split: train (first 5 rows)

,symbol,quarter,year,date,content,structured_content,company_name,company_id
0,A,4,2020,2020-11-23 16:30:00,"Operator: Good afternoon, and welcome to the A...","[{'speaker': 'Operator', 'text': 'Good afterno...","Agilent Technologies, Inc.",154924.0
1,A,3,2020,2020-08-18 16:30:00,"Operator: Good afternoon, and welcome to the A...","[{'speaker': 'Operator', 'text': 'Good afterno...","Agilent Technologies, Inc.",154924.0
2,A,2,2020,2020-05-21 16:30:00,"Operator: Good afternoon, and welcome to the A...","[{'speaker': 'Operator', 'text': 'Good afterno...","Agilent Technologies, Inc.",154924.0
3,A,1,2020,2020-02-18 16:30:00,Operator: Good afternoon and welcome to the Ag...,"[{'speaker': 'Operator', 'text': 'Good afterno...","Agilent Technologies, Inc.",154924.0
4,A,4,2021,2021-11-22 16:30:00,Operator: Good afternoon and welcome to the Ag...,"[{'speaker': 'Operator', 'text': 'Good afterno...","Agilent Technologies, Inc.",154924.0

In [5]:
if ds is None:
    print("Dataset is not available yet.")
else:
    primary_split = list(ds.keys())[0]
    subset = ds[primary_split]
    inspect_rows = min(10000, subset.num_rows)
    inspect_df = subset.select(range(inspect_rows)).to_pandas()

    print(f"Missing value stats on first {inspect_rows} rows of split '{primary_split}':")
    missing = inspect_df.isna().sum().sort_values(ascending=False)
    missing_ratio = (missing / inspect_rows).round(4)
    missing_summary = pd.DataFrame({"missing_count": missing, "missing_ratio": missing_ratio})
    display(missing_summary)

Missing value stats on first 10000 rows of split 'train':

                    missing_count  missing_ratio
symbol                          0            0.0
quarter                         0            0.0
year                            0            0.0
date                            0            0.0
content                         0            0.0
structured_content              0            0.0
company_name                    0            0.0
company_id                      0            0.0

In [6]:
if ds is None:
    print("Dataset is not available yet.")
else:
    primary_split = list(ds.keys())[0]
    subset = ds[primary_split]
    inspect_rows = min(10000, subset.num_rows)
    inspect_df = subset.select(range(inspect_rows)).to_pandas()

    text_candidates = [
        c for c in inspect_df.columns
        if any(k in c.lower() for k in ["transcript", "text", "content"])
    ]

    if not text_candidates:
        text_candidates = [
            c for c in inspect_df.columns
            if inspect_df[c].dtype == "object"
        ]

    if not text_candidates:
        print("No text-like column found for length statistics.")
    else:
        text_col = text_candidates[0]
        lengths = inspect_df[text_col].fillna("").astype(str).str.len()
        print(f"Text length statistics on column '{text_col}' (first {inspect_rows} rows):")
        print(lengths.describe(percentiles=[0.25, 0.5, 0.75, 0.9, 0.99]))

Text length statistics on column 'content' (first 10000 rows):
count     10000.000000
mean      52352.695200
std       11776.456536
min           0.000000
25%       46472.250000
50%       52704.500000
75%       57875.250000
90%       64626.100000
99%       84516.960000
max      226464.000000
Name: content, dtype: float64

## Date-Key Split (Keep Structured Content + Company Name)

- Use `date` as the split key.
- Keep only `structured_content` and `company_name` in each split payload.

In [7]:
if ds is None:
    print("Dataset is not available yet.")
else:
    required_cols = ["date", "symbol", "company_name", "structured_content"]
    split_df = ds["train"].to_pandas()[required_cols].copy()
    split_df["date"] = pd.to_datetime(split_df["date"], errors="coerce")

    # Only drop invalid date rows; keep rows even if symbol/company_name is missing
    split_df = split_df.dropna(subset=["date"]).sort_values("date").reset_index(drop=True)

    # Keep only data from 2020-05-01 to 2025-05-31 (exclusive upper bound: 2025-06-01)
    start_date = pd.Timestamp("2020-05-01")
    end_date_exclusive = pd.Timestamp("2025-06-01")
    split_df = split_df[(split_df["date"] >= start_date) & (split_df["date"] < end_date_exclusive)].copy()

    # Final schema
    split_df = split_df[["date", "symbol", "company_name", "structured_content"]].copy()

    date_key_series = split_df["date"].dt.strftime("%Y-%m-%d")
    date_keyed_data = (
        split_df.groupby(date_key_series, sort=True)[["symbol", "company_name", "structured_content"]]
        .apply(lambda g: g.to_dict(orient="records"))
        .to_dict()
    )

    date_split_summary = (
        split_df.groupby(date_key_series, sort=True)
        .size()
        .rename_axis("date_key")
        .reset_index(name="row_count")
    )

    print(f"Date window: {start_date.date()} to {(end_date_exclusive - pd.Timedelta(days=1)).date()}")
    print(f"Total rows kept: {len(split_df)}")
    print(f"Total unique date keys: {len(date_keyed_data)}")
    print("Columns kept in split_df:", split_df.columns.tolist())
    print("Missing symbol rows kept:", int(split_df["symbol"].isna().sum()))
    print("Missing company_name rows kept:", int(split_df["company_name"].isna().sum()))

Date window: 2020-05-01 to 2025-05-31
Total rows kept: 10759
Total unique date keys: 976
Columns kept in split_df: ['date', 'symbol', 'company_name', 'structured_content']
Missing symbol rows kept: 0
Missing company_name rows kept: 853

In [8]:
if ds is None:
    print("Dataset is not available yet.")
else:
    print("Date split summary (head):")
    display(date_split_summary.head(10))
    print("Date split summary (tail):")
    display(date_split_summary.tail(10))

    print("Filtered dataset preview (4 columns):")
    display(split_df.head(5))

    sample_date_key = date_split_summary.iloc[-1]["date_key"]
    sample_records = date_keyed_data[sample_date_key][:2]
    print(f"Sample date key: {sample_date_key}")
    print(f"Records on that date: {len(date_keyed_data[sample_date_key])}")
    print("First 2 records (symbol/company_name/structured_content):")
    sample_records

Date split summary (head):

     date_key  row_count
0  2020-05-01         34
1  2020-05-02          4
2  2020-05-04          9
3  2020-05-05         41
4  2020-05-06         39
5  2020-05-07         40
6  2020-05-08         30
7  2020-05-09         10
8  2020-05-10          9
9  2020-05-11         10

Date split summary (tail):

       date_key  row_count
966  2025-05-02         19
967  2025-05-05         11
968  2025-05-06         30
969  2025-05-07         26
970  2025-05-08         27
971  2025-05-09          1
972  2025-05-11          1
973  2025-05-12          4
974  2025-05-14          1
975  2025-05-15          4

Filtered dataset preview (4 columns):

,date,symbol,company_name,structured_content
22603,2020-05-01 01:12:35,NLSN,None,"[{'speaker': 'Operator', 'text': 'Ladies and g..."
22604,2020-05-01 07:30:00,JCI,Johnson Controls International plc,"[{'speaker': 'Operator', 'text': 'Welcome to J..."
22605,2020-05-01 08:00:00,MOH,"Molina Healthcare, Inc.","[{'speaker': 'Operator', 'text': 'Good day, an..."
22606,2020-05-01 08:00:00,WHR,None,"[{'speaker': 'Operator', 'text': 'Ladies and g..."
22607,2020-05-01 08:00:00,EMN,Eastman Chemical Company,"[{'speaker': 'Operator', 'text': 'Good day, ev..."

Sample date key: 2025-05-15
Records on that date: 4
First 2 records (symbol/company_name/structured_content):

In [9]:
split_df.head()

,date,symbol,company_name,structured_content
22603,2020-05-01 01:12:35,NLSN,None,"[{'speaker': 'Operator', 'text': 'Ladies and g..."
22604,2020-05-01 07:30:00,JCI,Johnson Controls International plc,"[{'speaker': 'Operator', 'text': 'Welcome to J..."
22605,2020-05-01 08:00:00,MOH,"Molina Healthcare, Inc.","[{'speaker': 'Operator', 'text': 'Good day, an..."
22606,2020-05-01 08:00:00,WHR,None,"[{'speaker': 'Operator', 'text': 'Ladies and g..."
22607,2020-05-01 08:00:00,EMN,Eastman Chemical Company,"[{'speaker': 'Operator', 'text': 'Good day, ev..."

## Unique Ticker Metadata (2020-05 to Latest)

Extract `ticker -> company/sector/industry` from `glopardo/sp500-earnings-transcripts` 
for records between `2020-05-01` and the latest available `earnings_date`.

In [10]:
META_DATASET_ID = "glopardo/sp500-earnings-transcripts"
meta_ds = load_dataset(META_DATASET_ID)

meta_cols = ["ticker", "company", "sector", "industry", "earnings_date"]
meta_df = meta_ds["train"].to_pandas()[meta_cols].copy()
meta_df["earnings_date"] = pd.to_datetime(meta_df["earnings_date"], errors="coerce")

meta_df = meta_df.dropna(subset=["earnings_date", "ticker"]).copy()
start_date = pd.Timestamp("2020-05-01")
latest_date = meta_df["earnings_date"].max()

meta_window_df = meta_df[(meta_df["earnings_date"] >= start_date) & (meta_df["earnings_date"] <= latest_date)].copy()

ticker_metadata_df = (
    meta_window_df.sort_values(["ticker", "earnings_date"])
    .drop_duplicates(subset=["ticker"], keep="last")
    [["ticker", "company", "sector", "industry"]]
    .sort_values("ticker")
    .reset_index(drop=True)
)

ticker_profile_count = (
    meta_window_df[["ticker", "company", "sector", "industry"]]
    .drop_duplicates()
    .groupby("ticker")
    .size()
    .rename("profile_count")
    .reset_index()
)
ticker_profile_conflicts = ticker_profile_count[ticker_profile_count["profile_count"] > 1].copy()

print(f"Loaded metadata dataset: {META_DATASET_ID}")
print(f"Date window: {start_date.date()} to {latest_date.date()}")
print(f"Rows in date window: {len(meta_window_df)}")
print(f"Unique tickers extracted: {ticker_metadata_df['ticker'].nunique()}")
print(f"Tickers with >1 metadata profile in window: {len(ticker_profile_conflicts)}")

Loaded metadata dataset: glopardo/sp500-earnings-transcripts
Date window: 2020-05-01 to 2025-02-03
Rows in date window: 9052
Unique tickers extracted: 496
Tickers with >1 metadata profile in window: 0

In [11]:
print("Unique ticker metadata preview:")
display(ticker_metadata_df.head(20))

if len(ticker_profile_conflicts) > 0:
    print("Sample ticker profile conflicts (same ticker with multiple company/sector/industry combinations):")
    display(ticker_profile_conflicts.head(20))
else:
    print("No ticker metadata conflicts detected in this date window.")

Unique ticker metadata preview:

,ticker,company,sector,industry
0,A,Agilent Technologies,Health Care,Life Sciences Tools & Services
1,AAPL,Apple Inc.,Information Technology,"Technology Hardware, Storage & Peripherals"
2,ABBV,AbbVie,Health Care,Biotechnology
3,ABNB,Airbnb,Consumer Discretionary,"Hotels, Resorts & Cruise Lines"
4,ABT,Abbott Laboratories,Health Care,Health Care Equipment
5,ACGL,Arch Capital Group,Financials,Property & Casualty Insurance
6,ACN,Accenture,Information Technology,IT Consulting & Other Services
7,ADBE,Adobe Inc.,Information Technology,Application Software
8,ADI,Analog Devices,Information Technology,Semiconductors
9,ADM,Archer Daniels Midland,Consumer Staples,Agricultural Products & Services
10,ADP,Automatic Data Processing,Industrials,Human Resource & Employment Services
11,ADSK,Autodesk,Information Technology,Application Software
12,AEE,Ameren,Utilities,Multi-Utilities
13,AEP,American Electric Power,Utilities,Electric Utilities
14,AES,AES Corporation,Utilities,Independent Power Producers & Energy Traders
15,AFL,Aflac,Financials,Life & Health Insurance
16,AIG,American International Group,Financials,Multi-line Insurance
17,AIZ,Assurant,Financials,Multi-line Insurance
18,AJG,Arthur J. Gallagher & Co.,Financials,Insurance Brokers
19,AKAM,Akamai Technologies,Information Technology,Internet Services & Infrastructure

No ticker metadata conflicts detected in this date window.

## Merge `split_df` with `ticker_metadata_df`

- Merge on `split_df.symbol == ticker_metadata_df.ticker`
- Fill missing `company_name` from metadata `company`
- Build final ticker-keyed table with `Company_name, sector, industry, date, structured_content`

In [12]:
required_vars = ["split_df", "ticker_metadata_df"]
missing_vars = [v for v in required_vars if v not in globals()]

if missing_vars:
    print(f"Missing variables: {missing_vars}. Please run previous cells first.")
else:
    merge_base_df = split_df.copy()
    merge_base_df["symbol_norm"] = merge_base_df["symbol"].astype("string").str.strip().str.upper()

    meta_lookup_df = ticker_metadata_df.copy()
    meta_lookup_df["ticker"] = meta_lookup_df["ticker"].astype("string").str.strip().str.upper()

    merged_df = merge_base_df.merge(meta_lookup_df, left_on="symbol_norm", right_on="ticker", how="left")

    company_name_clean = merged_df["company_name"].replace(r"^\s*$", pd.NA, regex=True)
    merged_df["Company_name"] = company_name_clean.combine_first(merged_df["company"])

    merged_df["ticker"] = merged_df["ticker"].combine_first(merged_df["symbol_norm"])

    final_ticker_df = merged_df[["ticker", "Company_name", "sector", "industry", "date", "structured_content"]].copy()
    final_ticker_df = final_ticker_df.sort_values(["ticker", "date"]).reset_index(drop=True)

    final_ticker_table = final_ticker_df.set_index("ticker")[["Company_name", "sector", "industry", "date", "structured_content"]]

    missing_company_before = int(company_name_clean.isna().sum())
    missing_company_after = int(final_ticker_df["Company_name"].isna().sum())

    print(f"Rows in final table: {len(final_ticker_table)}")
    print(f"Unique ticker keys: {final_ticker_df['ticker'].nunique(dropna=True)}")
    print(f"Missing Company_name before fill: {missing_company_before}")
    print(f"Missing Company_name after fill: {missing_company_after}")

Rows in final table: 10759
Unique ticker keys: 578
Missing Company_name before fill: 853
Missing Company_name after fill: 730

In [13]:
if "final_ticker_table" not in globals():
    print("`final_ticker_table` not found. Run previous merge cell first.")
else:
    print("Final ticker-keyed table preview:")
    display(final_ticker_table.head(20))

    unresolved_company = final_ticker_df[final_ticker_df["Company_name"].isna()]
    print(f"Rows still missing Company_name: {len(unresolved_company)}")
    if len(unresolved_company) > 0:
        display(unresolved_company[["ticker", "date"]].head(20))

Final ticker-keyed table preview:

,Company_name,sector,industry,date,structured_content
ticker,,,,,
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2020-05-21 16:30:00,"[{'speaker': 'Operator', 'text': 'Good afterno..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2020-08-18 16:30:00,"[{'speaker': 'Operator', 'text': 'Good afterno..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2020-11-23 16:30:00,"[{'speaker': 'Operator', 'text': 'Good afterno..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2021-02-16 16:30:00,"[{'speaker': 'Operator', 'text': 'Good afterno..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2021-05-25 16:30:00,"[{'speaker': 'Operator', 'text': 'Good afterno..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2021-08-17 16:30:00,"[{'speaker': 'Operator', 'text': 'Good afterno..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2021-11-22 16:30:00,"[{'speaker': 'Operator', 'text': 'Good afterno..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2022-02-22 16:30:00,"[{'speaker': 'Operator', 'text': 'Hello. And w..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2022-05-24 16:30:00,"[{'speaker': 'Operator', 'text': 'Good afterno..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2022-08-16 16:30:00,"[{'speaker': 'Operator', 'text': 'Good afterno..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2022-11-21 16:30:00,"[{'speaker': 'Operator', 'text': 'Ladies and g..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2023-02-28 08:30:00,"[{'speaker': 'Operator', 'text': 'Ladies and g..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2023-05-23 16:30:00,"[{'speaker': 'Operator', 'text': 'Ladies and g..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2023-08-15 16:30:00,"[{'speaker': 'Operator', 'text': 'Ladies and g..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2023-11-20 16:30:00,"[{'speaker': 'Operator', 'text': 'Ladies and g..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2024-02-27 16:30:00,"[{'speaker': 'Operator', 'text': 'Ladies and g..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2024-05-29 16:30:00,"[{'speaker': 'Operator', 'text': 'Ladies and g..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2024-08-21 16:30:00,"[{'speaker': 'Operator', 'text': 'Ladies and g..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2024-11-25 16:30:00,"[{'speaker': 'Operator', 'text': 'Good afterno..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2025-02-26 16:30:00,"[{'speaker': 'Operator', 'text': 'Good afterno..."

Rows still missing Company_name: 730

   ticker                date
20    AAL 2020-07-23 08:30:00
21    AAL 2020-10-22 08:30:00
22    AAL 2021-01-28 08:30:00
23    AAL 2021-04-22 10:30:00
24    AAL 2021-07-22 08:30:00
25    AAL 2021-10-21 08:30:00
26    AAL 2022-01-20 08:30:00
27    AAL 2022-04-21 10:30:00
28    AAL 2022-07-21 08:30:00
29    AAL 2022-10-20 08:30:00
30    AAL 2023-01-26 08:30:00
31    AAL 2023-04-27 13:05:00
32    AAL 2023-07-20 08:30:00
33    AAL 2023-10-19 08:30:00
34    AAL 2024-01-25 08:30:00
35    AAL 2024-04-25 09:15:00
36    AAL 2024-07-25 08:30:00
37    AAL 2024-10-24 08:30:00
38    AAL 2025-01-23 08:30:00
39    AAP 2020-05-19 08:00:00

## Fill Remaining Missing `Company_name` via Online Lookup + Manual Overrides

Use Yahoo Finance search API for unresolved tickers, then use manual overrides for delisted/renamed symbols.

In [14]:
import requests
from urllib.parse import quote

if "final_ticker_df" not in globals():
    print("`final_ticker_df` not found. Please run previous merge cells first.")
else:
    df_fill = final_ticker_df.copy()
    df_fill["ticker"] = df_fill["ticker"].astype("string").str.strip().str.upper()

    missing_mask_before = df_fill["Company_name"].isna() | df_fill["Company_name"].astype(str).str.strip().eq("")
    unresolved_tickers_before = sorted(df_fill.loc[missing_mask_before, "ticker"].dropna().unique().tolist())

    def yahoo_company_lookup(ticker: str, session: requests.Session) -> str | None:
        url = f"https://query1.finance.yahoo.com/v1/finance/search?q={quote(ticker)}"
        try:
            resp = session.get(url, timeout=15)
            resp.raise_for_status()
            payload = resp.json()
        except Exception:
            return None

        quotes = payload.get("quotes", []) or []

        # Strict match: exact symbol + equity type
        for q in quotes:
            symbol = str(q.get("symbol") or "").upper().strip()
            qtype = str(q.get("quoteType") or "").upper().strip()
            if symbol == ticker and qtype == "EQUITY":
                name = q.get("longname") or q.get("shortname")
                if isinstance(name, str) and name.strip():
                    return name.strip()

        return None

    session = requests.Session()
    session.headers.update({"User-Agent": "Mozilla/5.0"})

    yahoo_fill_map = {}
    for t in unresolved_tickers_before:
        name = yahoo_company_lookup(t, session)
        if name:
            yahoo_fill_map[t] = name

    # Manual overrides for delisted/renamed tickers and known edge cases
    manual_company_overrides = {
        "ABMD": "Abiomed, Inc.",
        "ADS": "Alliance Data Systems Corporation",
        "ALXN": "Alexion Pharmaceuticals, Inc.",
        "ATVI": "Activision Blizzard, Inc.",
        "CERN": "Cerner Corporation",
        "CTLT": "Catalent, Inc.",
        "CXO": "Concho Resources Inc.",
        "DISCK": "Discovery, Inc.",
        "DISH": "DISH Network Corporation",
        "DRE": "Duke Realty Corporation",
        "FLIR": "FLIR Systems, Inc.",
        "FRC": "First Republic Bank",
        "HBI": "Hanesbrands Inc.",
        "HFC": "HollyFrontier Corporation",
        "INFO": "IHS Markit Ltd.",
        "JWN": "Nordstrom, Inc.",
        "KSU": "Kansas City Southern",
        "MRO": "Marathon Oil Corporation",
        "NBL": "Noble Energy, Inc.",
        "NLSN": "Nielsen Holdings plc",
        "PBCT": "People's United Financial, Inc.",
        "PXD": "Pioneer Natural Resources Company",
        "SIVB": "SVB Financial Group",
        "TWTR": "Twitter, Inc.",
        "VAR": "Varian Medical Systems, Inc.",
        "WRK": "WestRock Company",
        "XEC": "Cimarex Energy Co.",
        "XLNX": "Xilinx, Inc.",
    }

    company_name_fill_map = {}
    for t in unresolved_tickers_before:
        company_name_fill_map[t] = manual_company_overrides.get(t) or yahoo_fill_map.get(t)

    fill_mask = missing_mask_before
    candidate_fill = df_fill.loc[fill_mask, "ticker"].map(company_name_fill_map)
    df_fill.loc[fill_mask, "Company_name"] = df_fill.loc[fill_mask, "Company_name"].combine_first(candidate_fill)

    missing_mask_after = df_fill["Company_name"].isna() | df_fill["Company_name"].astype(str).str.strip().eq("")
    unresolved_tickers_after = sorted(df_fill.loc[missing_mask_after, "ticker"].dropna().unique().tolist())

    # Overwrite final artifacts for downstream reproducibility
    final_ticker_df = df_fill.copy()
    final_ticker_table = final_ticker_df.set_index("ticker")[["Company_name", "sector", "industry", "date", "structured_content"]]

    print(f"Unresolved unique tickers before online fill: {len(unresolved_tickers_before)}")
    print(f"Yahoo auto-filled tickers: {len([k for k,v in yahoo_fill_map.items() if v])}")
    print(f"Manual override candidates available: {len(manual_company_overrides)}")
    print(f"Unresolved unique tickers after fill: {len(unresolved_tickers_after)}")

Unresolved unique tickers before online fill: 76
Yahoo auto-filled tickers: 48
Manual override candidates available: 28
Unresolved unique tickers after fill: 0

In [15]:
if "final_ticker_df" not in globals():
    print("`final_ticker_df` not found.")
else:
    missing_after = final_ticker_df[final_ticker_df["Company_name"].isna() | final_ticker_df["Company_name"].astype(str).str.strip().eq("")]
    unresolved_unique_after = sorted(missing_after["ticker"].dropna().unique().tolist())

    print(f"Remaining missing rows: {len(missing_after)}")
    print(f"Remaining missing unique tickers: {len(unresolved_unique_after)}")
    if unresolved_unique_after:
        print("Remaining unresolved tickers:")
        print(",".join(unresolved_unique_after))

    print("Updated final table preview:")
    display(final_ticker_table.head(20))

Remaining missing rows: 0
Remaining missing unique tickers: 0
Updated final table preview:

,Company_name,sector,industry,date,structured_content
ticker,,,,,
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2020-05-21 16:30:00,"[{'speaker': 'Operator', 'text': 'Good afterno..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2020-08-18 16:30:00,"[{'speaker': 'Operator', 'text': 'Good afterno..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2020-11-23 16:30:00,"[{'speaker': 'Operator', 'text': 'Good afterno..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2021-02-16 16:30:00,"[{'speaker': 'Operator', 'text': 'Good afterno..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2021-05-25 16:30:00,"[{'speaker': 'Operator', 'text': 'Good afterno..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2021-08-17 16:30:00,"[{'speaker': 'Operator', 'text': 'Good afterno..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2021-11-22 16:30:00,"[{'speaker': 'Operator', 'text': 'Good afterno..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2022-02-22 16:30:00,"[{'speaker': 'Operator', 'text': 'Hello. And w..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2022-05-24 16:30:00,"[{'speaker': 'Operator', 'text': 'Good afterno..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2022-08-16 16:30:00,"[{'speaker': 'Operator', 'text': 'Good afterno..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2022-11-21 16:30:00,"[{'speaker': 'Operator', 'text': 'Ladies and g..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2023-02-28 08:30:00,"[{'speaker': 'Operator', 'text': 'Ladies and g..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2023-05-23 16:30:00,"[{'speaker': 'Operator', 'text': 'Ladies and g..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2023-08-15 16:30:00,"[{'speaker': 'Operator', 'text': 'Ladies and g..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2023-11-20 16:30:00,"[{'speaker': 'Operator', 'text': 'Ladies and g..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2024-02-27 16:30:00,"[{'speaker': 'Operator', 'text': 'Ladies and g..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2024-05-29 16:30:00,"[{'speaker': 'Operator', 'text': 'Ladies and g..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2024-08-21 16:30:00,"[{'speaker': 'Operator', 'text': 'Ladies and g..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2024-11-25 16:30:00,"[{'speaker': 'Operator', 'text': 'Good afterno..."
A,"Agilent Technologies, Inc.",Health Care,Life Sciences Tools & Services,2025-02-26 16:30:00,"[{'speaker': 'Operator', 'text': 'Good afterno..."

## Final Sector/Industry Standardization (Deterministic, Reproducible)

This is the only retained method for `sector` / `industry` completion and standardization.
It follows the strict two-method policy:
1. `gics_reference` direct mapping
2. `manual_mapping_table` for non-reference tickers

In [16]:
if "final_ticker_df" not in globals():
    print("`final_ticker_df` not found. Run previous cells first.")
else:
    std_df = final_ticker_df.copy()
    std_df["ticker"] = std_df["ticker"].astype("string").str.strip().str.upper()

    gics_ref = load_dataset("jwigginton/index-constituents-sp500")["train"].to_pandas()
    gics_ref["symbol"] = gics_ref["symbol"].astype(str).str.strip().str.upper()
    gics_ref_map = (
        gics_ref[["symbol", "gics_sector", "gics_sub_industry"]]
        .drop_duplicates(subset=["symbol"], keep="last")
        .set_index("symbol")
        .to_dict(orient="index")
    )

    # Fixed base labels for non-reference tickers (manually curated table)
    manual_ticker_base_map = {
        "AAP": ("Consumer Discretionary", "Auto Parts"),
        "ABMD": ("Health Care", "Surgical & Medical Instruments"),
        "ADS": ("Financials", "Personal Credit Institutions"),
        "AIV": ("Real Estate", "REIT - Residential"),
        "ALK": ("Industrials", "Airlines"),
        "ALXN": ("Health Care", "Pharmaceutical Preparations"),
        "AMTM": ("Industrials", "Specialty Business Services"),
        "APO": ("Financials", "Asset Management & Custody Banks"),
        "ATVI": ("Communication Services", "Electronic Gaming & Multimedia"),
        "CERN": ("Information Technology", "Computer Integrated Systems Design"),
        "COTY": ("Consumer Staples", "Household & Personal Products"),
        "CPAY": ("Financials", "Transaction & Payment Processing Services"),
        "CPRI": ("Consumer Discretionary", "Luxury Goods"),
        "CRWD": ("Information Technology", "Systems Software"),
        "CXO": ("Energy", "Oil & Gas Exploration & Production"),
        "DASH": ("Consumer Discretionary", "Internet Retail"),
        "DECK": ("Consumer Discretionary", "Footwear"),
        "DELL": ("Information Technology", "Technology Hardware, Storage & Peripherals"),
        "DISCK": ("Communication Services", "Cable & Other Pay Television Services"),
        "DISH": ("Communication Services", "Telecom Services"),
        "DOC": ("Real Estate", "Health Care REITs"),
        "DRE": ("Real Estate", "Real Estate Investment Trusts"),
        "DXC": ("Technology", "Information Technology Services"),
        "ERIE": ("Financials", "Insurance Brokers"),
        "EXE": ("Energy", "Oil & Gas Exploration & Production"),
        "FBIN": ("Industrials", "Building Products & Equipment"),
        "FLIR": ("Information Technology", "Scientific & Technical Instruments"),
        "FLS": ("Industrials", "Specialty Industrial Machinery"),
        "FRC": ("Financials", "Banks - Regional"),
        "FTI": ("Energy", "Oil & Gas Equipment & Services"),
        "GDDY": ("Information Technology", "Internet Services & Infrastructure"),
        "GEV": ("Industrials", "Heavy Electrical Equipment"),
        "HBI": ("Consumer Discretionary", "Apparel Manufacturing"),
        "HFC": ("Energy", "Petroleum Refining"),
        "HOG": ("Consumer Discretionary", "Recreational Vehicles"),
        "HP": ("Energy", "Oil & Gas Drilling"),
        "HRB": ("Consumer Discretionary", "Personal Services"),
        "INFO": ("Information Technology", "Computer Programming & Data Processing"),
        "IPGP": ("Technology", "Semiconductor Equipment & Materials"),
        "JWN": ("Consumer Discretionary", "Department Stores"),
        "KKR": ("Financials", "Asset Management & Custody Banks"),
        "KSS": ("Consumer Discretionary", "Department Stores"),
        "KSU": ("Industrials", "Railroads"),
        "LEG": ("Consumer Discretionary", "Furnishings, Fixtures & Appliances"),
        "LII": ("Industrials", "Building Products"),
        "LNC": ("Financials", "Insurance - Life"),
        "LUMN": ("Communication Services", "Telecom Services"),
        "M": ("Consumer Discretionary", "Department Stores"),
        "MBC": ("Consumer Discretionary", "Furnishings, Fixtures & Appliances"),
        "NBL": ("Energy", "Oil & Gas Exploration & Production"),
        "NLSN": ("Industrials", "Business Services"),
        "NOV": ("Energy", "Oil & Gas Equipment & Services"),
        "NWL": ("Consumer Staples", "Household & Personal Products"),
        "OGN": ("Healthcare", "Drug Manufacturers - General"),
        "PBCT": ("Financials", "Banks - Regional"),
        "PENN": ("Consumer Discretionary", "Resorts & Casinos"),
        "PLTR": ("Information Technology", "Internet Services & Infrastructure"),
        "PRGO": ("Healthcare", "Drug Manufacturers - Specialty & Generic"),
        "PVH": ("Consumer Discretionary", "Apparel Manufacturing"),
        "SBNY": ("Financials", "Banks - Regional"),
        "SEDG": ("Technology", "Solar"),
        "SEE": ("Consumer Discretionary", "Packaging & Containers"),
        "SIVB": ("Financials", "Financials"),
        "SLG": ("Real Estate", "REIT - Office"),
        "SMCI": ("Information Technology", "Technology Hardware, Storage & Peripherals"),
        "SOLV": ("Health Care", "Health Care Technology"),
        "SW": ("Consumer Discretionary", "Packaging & Containers"),
        "TKO": ("Communication Services", "Entertainment"),
        "TPL": ("Energy", "Oil & Gas Exploration & Production"),
        "TWTR": ("Communication Services", "Internet Content & Information"),
        "UA": ("Consumer Discretionary", "Apparel Manufacturing"),
        "UNM": ("Financials", "Insurance - Life"),
        "VAR": ("Health Care", "Electromedical & Electrotherapeutic Apparatus"),
        "VNO": ("Real Estate", "REIT - Office"),
        "VNT": ("Technology", "Scientific & Technical Instruments"),
        "VST": ("Utilities", "Electric Utilities"),
        "WDAY": ("Information Technology", "Application Software"),
        "WSM": ("Consumer Discretionary", "Specialty Retail"),
        "WU": ("Financials", "Credit Services"),
        "XEC": ("Energy", "Oil & Gas Exploration & Production"),
        "XLNX": ("Information Technology", "Semiconductors & Related Devices"),
        "XRX": ("Industrials", "Business Equipment & Supplies"),
    }

    sector_manual_map = {
        "Technology": "Information Technology",
        "Healthcare": "Health Care",
    }

    industry_manual_map = {
        "Airlines": "Passenger Airlines",
        "Apparel Manufacturing": "Apparel, Accessories & Luxury Goods",
        "Auto Parts": "Automotive Retail",
        "Banks - Regional": "Regional Banks",
        "Building Products & Equipment": "Building Products",
        "Business Equipment & Supplies": "Technology Hardware, Storage & Peripherals",
        "Business Services": "Research & Consulting Services",
        "Cable & Other Pay Television Services": "Cable & Satellite",
        "Computer Integrated Systems Design": "IT Consulting & Other Services",
        "Computer Programming & Data Processing": "Data Processing & Outsourced Services",
        "Credit Services": "Transaction & Payment Processing Services",
        "Department Stores": "Broadline Retail",
        "Drug Manufacturers - General": "Pharmaceuticals",
        "Drug Manufacturers - Specialty & Generic": "Pharmaceuticals",
        "Electromedical & Electrotherapeutic Apparatus": "Health Care Equipment",
        "Electronic Gaming & Multimedia": "Interactive Home Entertainment",
        "Entertainment": "Movies & Entertainment",
        "Financials": "Regional Banks",
        "Footwear": "Apparel, Accessories & Luxury Goods",
        "Furnishings, Fixtures & Appliances": "Home Furnishings",
        "Health Care Technology": "Health Care Equipment",
        "Heavy Electrical Equipment": "Electrical Components & Equipment",
        "Household & Personal Products": "Household Products",
        "Information Technology Services": "IT Consulting & Other Services",
        "Insurance - Life": "Life & Health Insurance",
        "Internet Content & Information": "Interactive Media & Services",
        "Internet Retail": "Broadline Retail",
        "Luxury Goods": "Apparel, Accessories & Luxury Goods",
        "Oil & Gas Drilling": "Oil & Gas Equipment & Services",
        "Packaging & Containers": "Paper & Plastic Packaging Products & Materials",
        "Personal Credit Institutions": "Consumer Finance",
        "Personal Services": "Other Specialty Retail",
        "Petroleum Refining": "Oil & Gas Refining & Marketing",
        "Pharmaceutical Preparations": "Pharmaceuticals",
        "REIT - Office": "Office REITs",
        "REIT - Residential": "Multi-Family Residential REITs",
        "Railroads": "Rail Transportation",
        "Real Estate Investment Trusts": "Other Specialized REITs",
        "Recreational Vehicles": "Leisure Products",
        "Resorts & Casinos": "Casinos & Gaming",
        "Scientific & Technical Instruments": "Electronic Equipment & Instruments",
        "Semiconductor Equipment & Materials": "Semiconductor Materials & Equipment",
        "Semiconductors & Related Devices": "Semiconductors",
        "Solar": "Semiconductor Materials & Equipment",
        "Specialty Business Services": "Diversified Support Services",
        "Specialty Industrial Machinery": "Industrial Machinery & Supplies & Components",
        "Specialty Retail": "Other Specialty Retail",
        "Surgical & Medical Instruments": "Health Care Equipment",
        "Telecom Services": "Integrated Telecommunication Services",
    }

    sec_std = []
    ind_std = []
    src_std = []
    conf_std = []

    for _, row in std_df.iterrows():
        t = row["ticker"]
        if t in gics_ref_map:
            sec_std.append(gics_ref_map[t]["gics_sector"])
            ind_std.append(gics_ref_map[t]["gics_sub_industry"])
            src_std.append("gics_reference")
            conf_std.append("high")
        else:
            if t in manual_ticker_base_map:
                raw_sec, raw_ind = manual_ticker_base_map[t]
                src_std.append("manual_mapping_table")
                conf_std.append("high")
            else:
                raw_sec = row.get("sector")
                raw_ind = row.get("industry")
                src_std.append("manual_mapping_table")
                conf_std.append("medium")

            raw_sec = "" if pd.isna(raw_sec) else str(raw_sec).strip()
            raw_ind = "" if pd.isna(raw_ind) else str(raw_ind).strip()

            sec = sector_manual_map.get(raw_sec, raw_sec)
            ind = industry_manual_map.get(raw_ind, raw_ind)

            sec_std.append(sec if sec else pd.NA)
            ind_std.append(ind if ind else pd.NA)

    std_df["sector_std"] = sec_std
    std_df["industry_std"] = ind_std
    std_df["classification_source"] = src_std
    std_df["classification_confidence"] = conf_std

    final_ticker_std_df = std_df.copy()
    final_ticker_std_table = final_ticker_std_df.set_index("ticker")[["Company_name", "sector_std", "industry_std", "date", "structured_content", "classification_source", "classification_confidence"]]

    print("Deterministic standardization complete.")
    print(f"Rows: {len(final_ticker_std_df)}")
    print(f"Unique tickers: {final_ticker_std_df['ticker'].nunique()}")

Deterministic standardization complete.
Rows: 10759
Unique tickers: 578

In [17]:
if "final_ticker_std_df" not in globals():
    print("`final_ticker_std_df` not found.")
else:
    sec_m = final_ticker_std_df["sector_std"].isna() | final_ticker_std_df["sector_std"].astype(str).str.strip().eq("")
    ind_m = final_ticker_std_df["industry_std"].isna() | final_ticker_std_df["industry_std"].astype(str).str.strip().eq("")

    gics_ref = load_dataset("jwigginton/index-constituents-sp500")["train"].to_pandas()
    valid_sec = set(gics_ref["gics_sector"].dropna().astype(str).str.strip())
    valid_ind = set(gics_ref["gics_sub_industry"].dropna().astype(str).str.strip())

    bad_sec = sorted(set(final_ticker_std_df["sector_std"].dropna().astype(str).str.strip()) - valid_sec)
    bad_ind = sorted(set(final_ticker_std_df["industry_std"].dropna().astype(str).str.strip()) - valid_ind)

    print(f"Missing sector_std rows: {int(sec_m.sum())}")
    print(f"Missing industry_std rows: {int(ind_m.sum())}")
    print(f"Missing std unique tickers: {final_ticker_std_df.loc[sec_m | ind_m, 'ticker'].nunique()}")
    print(f"Invalid sector_std labels: {len(bad_sec)}")
    if bad_sec: print(bad_sec)
    print(f"Invalid industry_std labels: {len(bad_ind)}")
    if bad_ind: print(bad_ind)

    print("classification_source distribution:")
    display(final_ticker_std_df["classification_source"].value_counts())

Missing sector_std rows: 0
Missing industry_std rows: 0
Missing std unique tickers: 0
Invalid sector_std labels: 0
Invalid industry_std labels: 0
classification_source distribution:

classification_source
gics_reference          9946
manual_mapping_table     813
Name: count, dtype: int64

## Final Complete Dataset

Build a single final table and validate missing values for key columns.

In [18]:
if "final_ticker_std_df" not in globals():
    print("`final_ticker_std_df` not found. Run previous cells first.")
else:
    final_dataset_df = final_ticker_std_df.copy()
    final_dataset_df["ticker"] = final_dataset_df["ticker"].astype("string").str.strip().str.upper()
    final_dataset_df["Company_name"] = final_dataset_df["Company_name"].replace(r"^\s*$", pd.NA, regex=True)
    final_dataset_df["date"] = pd.to_datetime(final_dataset_df["date"], errors="coerce")

    final_dataset_df = final_dataset_df.assign(
        sector=final_dataset_df["sector_std"],
        industry=final_dataset_df["industry_std"],
    )[["ticker", "Company_name", "sector", "industry", "date", "structured_content"]]
    final_dataset_df = final_dataset_df.sort_values(["date", "ticker"]).reset_index(drop=True)

    key_missing = final_dataset_df[["ticker", "sector", "industry", "date", "structured_content"]].isna().sum()
    print("Missing values in key columns:")
    display(key_missing.to_frame("missing_count"))

    print(f"Total rows: {len(final_dataset_df)}")
    print(f"Unique tickers: {final_dataset_df['ticker'].nunique(dropna=True)}")
    print(f"Date range: {final_dataset_df['date'].min()} -> {final_dataset_df['date'].max()}")
    display(final_dataset_df.head(20))

Missing values in key columns:

                    missing_count
ticker                          0
sector                          0
industry                        0
date                            0
structured_content              0

Total rows: 10759
Unique tickers: 578
Date range: 2020-05-01 01:12:35 -> 2025-05-15 16:30:00

,ticker,Company_name,sector,industry,date,structured_content
0,NLSN,Nielsen Holdings plc,Industrials,Research & Consulting Services,2020-05-01 01:12:35,"[{'speaker': 'Operator', 'text': 'Ladies and g..."
1,JCI,Johnson Controls International plc,Industrials,Building Products,2020-05-01 07:30:00,"[{'speaker': 'Operator', 'text': 'Welcome to J..."
2,EMN,Eastman Chemical Company,Materials,Specialty Chemicals,2020-05-01 08:00:00,"[{'speaker': 'Operator', 'text': 'Good day, ev..."
3,MOH,"Molina Healthcare, Inc.",Health Care,Managed Health Care,2020-05-01 08:00:00,"[{'speaker': 'Operator', 'text': 'Good day, an..."
4,WHR,Whirlpool Corporation,Consumer Discretionary,Household Appliances,2020-05-01 08:00:00,"[{'speaker': 'Operator', 'text': 'Ladies and g..."
5,RJF,"Raymond James Financial, Inc.",Financials,Investment Banking & Brokerage,2020-05-01 08:15:00,"[{'speaker': 'Kristie Waugh', 'text': 'Good mo..."
6,AON,Aon plc,Financials,Insurance Brokers,2020-05-01 08:30:00,"[{'speaker': 'Operator', 'text': 'Good morning..."
7,CBOE,"Cboe Global Markets, Inc.",Financials,Financial Exchanges & Data,2020-05-01 08:30:00,"[{'speaker': 'Operator', 'text': 'Hello, and w..."
8,CHTR,"Charter Communications, Inc.",Communication Services,Cable & Satellite,2020-05-01 08:30:00,"[{'speaker': 'Operator', 'text': 'Ladies and g..."
9,CL,Colgate-Palmolive Company,Consumer Staples,Household Products,2020-05-01 08:30:00,"[{'speaker': 'Operator', 'text': 'Good morning..."
10,HON,Honeywell International Inc.,Industrials,Industrial Conglomerates,2020-05-01 08:30:00,"[{'speaker': 'Operator', 'text': 'Good day, la..."
11,ABBV,AbbVie Inc.,Health Care,Biotechnology,2020-05-01 09:00:00,"[{'speaker': 'Operator', 'text': 'Good morning..."
12,COR,"Cencora, Inc.",Health Care,Health Care Distributors,2020-05-01 09:00:00,"[{'speaker': 'Operator', 'text': 'Greetings, a..."
13,TECH,Bio-Techne Corporation,Health Care,Life Sciences Tools & Services,2020-05-01 09:00:00,"[{'speaker': 'Operator', 'text': 'Good morning..."
14,CTRA,Coterra Energy Inc.,Energy,Oil & Gas Exploration & Production,2020-05-01 09:30:00,"[{'speaker': 'Operator', 'text': 'Good morning..."
15,EL,The Estée Lauder Companies Inc.,Consumer Staples,Personal Care Products,2020-05-01 09:30:00,"[{'speaker': 'Operator', 'text': 'Good day, ev..."
16,XOM,Exxon Mobil Corporation,Energy,Integrated Oil & Gas,2020-05-01 09:30:00,"[{'speaker': 'Operator', 'text': 'Good day, ev..."
17,APO,"Apollo Global Management, Inc.",Financials,Asset Management & Custody Banks,2020-05-01 10:00:00,"[{'speaker': 'Operator', 'text': 'Good morning..."
18,BLDR,"Builders FirstSource, Inc.",Industrials,Building Products,2020-05-01 10:00:00,"[{'speaker': 'Operator', 'text': 'Good morning..."
19,UAL,"United Airlines Holdings, Inc.",Industrials,Passenger Airlines,2020-05-01 10:00:00,"[{'speaker': 'Operator', 'text': 'Good morning..."

In [20]:
# Save final_dataset_df to CSV
if "final_dataset_df" not in globals():
    print("`final_dataset_df` not found. Run previous cells first.")
else:
    output_path = "final_dataset.csv"
    final_dataset_df.to_csv(output_path, index=False, encoding="utf-8-sig")
    print(f"Saved final_dataset_df to: {output_path}")
    print(f"Total rows exported: {len(final_dataset_df)}")

Saved final_dataset_df to: final_dataset.csv
Total rows exported: 10759